name: Publish a test procedure release

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * *'

jobs:
  procedure-perform-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config user.email "actions-bot@github.com"
          git config user.name "GitHub Actions (run by ${{ github.actor }})"
